/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_AHB1ENR     0x40023830
#define GPIOA_MODER     0x40020000
#define GPIOA_ODR       0x40020014

int main(void)
{
    // Enable GPIOA clock (bit 0)
    uint32_t* pRCC_AHB1ENR = (uint32_t*)RCC_AHB1ENR;
    *pRCC_AHB1ENR |= (1 << 0);

    // Set PA1 to output mode (bits 3:2 = 01)
    uint32_t* pGPIOA_MODER = (uint32_t*)GPIOA_MODER;
    *pGPIOA_MODER |= (1 << 2);

    // Blink PA1
    uint32_t* pGPIOA_ODR = (uint32_t*)GPIOA_ODR;

    for(;;)
    {
        *pGPIOA_ODR |= (1 << 1);
        for(uint32_t i = 0; i < 500000; i++);
        *pGPIOA_ODR &= ~(1 << 1);
        for(uint32_t i = 0; i < 500000; i++);
    }
}
