/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>


///////////////////////////////////////////////////////////////////////////////////////////
//  Implementation of printf like feature using ARM Cortex M3/M4 ITM functionality
//  This function will not work for ARM Cortex M0/M0+
//  If you are using Cortex M0, then you can use semihosting feature of openOCD
///////////////////////////////////////////////////////////////////////////////////////////
//
//  HOW PRINTF WORKS ON THIS BOARD (the full path):
//
//  printf("Hello")
//      |
//      v
//  C standard library (provided by toolchain)
//      |
//      v
//  write() function in syscalls.c  <-- we modify this to call ITM_SendChar
//      |
//      v
//  ITM_SendChar('H'), ITM_SendChar('e'), ITM_SendChar('l')... one character at a time
//      |
//      v
//  Character goes into ITM FIFO (a small hardware queue inside the processor)
//      |
//      v
//  ITM passes it to TPIU (formats the data for output)
//      |
//      v
//  TPIU pushes it out the SWO wire (1 physical pin on the F407 chip)
//      |
//      v
//  ST-LINK receives it (the F103 debugger chip on the board)
//      |
//      v
//  ST-LINK sends it over USB to your laptop
//      |
//      v
//  IDE's SWO/ITM console displays "Hello"
//
//  ALL of this happens while your code keeps running at full speed.
//  The processor does NOT stop. This is the advantage over semihosting.
//
///////////////////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////////////////
//  REGISTER ADDRESSES
//
//  These are not normal variables. These are physical hardware registers inside
//  the Cortex-M4 processor. Writing to these addresses talks directly to the
//  debug hardware — not to RAM.
//
//  "volatile" tells the compiler: "don't optimize away reads/writes to this
//  address — the hardware can change it at any time behind your back."
///////////////////////////////////////////////////////////////////////////////////////////


// DEMCR - Debug Exception and Monitor Control Register
// Address: 0xE000EDFC
// This is the MASTER POWER SWITCH for the entire CoreSight debug/trace system.
// CoreSight includes: ITM, TPIU, DWT — all the debug hardware.
// Until you turn this on, none of the trace hardware will respond.
// Think of it like the breaker panel in a house — everything is dark until you flip it.
#define DEMCR                *((volatile uint32_t*) 0xE000EDFCU )


// ITM_STIMULUS_PORT0 - ITM Stimulus Port 0 Register
// Address: 0xE0000000
// This register does DOUBLE DUTY:
//   READING from it  --> checks if the FIFO has space (bit 0: 1=ready, 0=full)
//   WRITING to it    --> drops a character into the FIFO (the mailbox)
// The FIFO is a small hardware queue (First In First Out).
// Characters buffer here if your code sends them faster than the
// TPIU can push them out the SWO wire.
// 'H' goes in first, comes out first. 'e' goes in second, comes out second.
#define ITM_STIMULUS_PORT0   *((volatile uint32_t*) 0xE0000000 )


// ITM_TRACE_EN - ITM Trace Enable Register
// Address: 0xE0000E00
// The ITM has 32 mailbox slots called "stimulus ports" (port 0 through port 31).
// Each port is an independent channel. For example:
//   Port 0 = printf output (the standard one)
//   Other ports could carry DWT timing data, diagnostic info, etc.
// By default ALL 32 ports are OFF. This register is the gatekeeper.
// It's a 32-bit register — one bit per port. Set bit N to 1 to enable port N.
// Think of it like unlocking a specific room in the house (after the breaker is on).
#define ITM_TRACE_EN         *((volatile uint32_t*) 0xE0000E00 )


///////////////////////////////////////////////////////////////////////////////////////////
//  ITM_SendChar function
//
//  Sends ONE character to the ITM FIFO.
//  Called repeatedly by write() in syscalls.c — once per character.
//  For "Hello", write() calls this 5 times: 'H', 'e', 'l', 'l', 'o'
//
//  uint8_t = unsigned 8-bit integer = exactly the size of one ASCII character
///////////////////////////////////////////////////////////////////////////////////////////

void ITM_SendChar(uint8_t ch)
{

    ///////////////////////////////////////////////////////////////////////////////////
    //  STEP 1: FLIP THE BREAKER — Turn on the entire trace system
    ///////////////////////////////////////////////////////////////////////////////////
    //
    //  DEMCR is a 32-bit register. Bit 24 is called TRCENA (Trace Enable).
    //  Setting bit 24 to 1 powers on the ITM, TPIU, and DWT.
    //
    //  (1 << 24) in binary:
    //
    //    Bit:  31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0
    //          [0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
    //                               ^
    //                               |
    //                           TRCENA = 1  -->  "Turn on the entire CoreSight trace system"
    //
    //  |= means "set this bit to 1 without changing any other bits in the register"
    //
    //  This runs every time a character is sent. Setting a bit that's already set
    //  does nothing harmful — it's simpler than checking first.
    //
    DEMCR |= ( 1 << 24);


    ///////////////////////////////////////////////////////////////////////////////////
    //  STEP 2: UNLOCK THE ROOM — Enable stimulus port 0
    ///////////////////////////////////////////////////////////////////////////////////
    //
    //  ITM_TRACE_EN is a 32-bit register. Each bit controls one port.
    //  Bit 0 = port 0, Bit 1 = port 1, ... Bit 31 = port 31.
    //  We only need port 0 for printf.
    //
    //  (1 << 0) in binary:
    //
    //    Bit:  31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0
    //          [0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
    //                                                                                                         ^
    //                                                                                                         |
    //                                                                                              Port 0 = 1  -->  "Port 0 is open for business"
    //
    //  Note: (1 << 0) is the same as just writing 1.
    //  It's written this way as an embedded convention for readability.
    //  (1 << 0) clearly says "I'm setting bit 0".
    //  (1 << 5) would mean "I'm setting bit 5" to enable port 5.
    //
    ITM_TRACE_EN |= ( 1 << 0);


    ///////////////////////////////////////////////////////////////////////////////////
    //  STEP 3: WAIT IN LINE — Check if the FIFO has space
    ///////////////////////////////////////////////////////////////////////////////////
    //
    //  Before dropping a character in, we READ from stimulus port 0 to check
    //  if the FIFO is ready. Bit 0 of the read value tells us:
    //
    //    If FIFO is READY (has space):
    //
    //    Bit:  31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0
    //          [x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  1]
    //                                                                                                            ^
    //                                                                                                            |
    //                                                                                                 Bit 0 = 1  -->  "FIFO ready, you can write"
    //
    //    If FIFO is FULL (no space):
    //
    //    Bit:  31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0
    //          [x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  0]
    //                                                                                                            ^
    //                                                                                                            |
    //                                                                                                 Bit 0 = 0  -->  "FIFO full, wait!"
    //
    //  (ITM_STIMULUS_PORT0 & 1) isolates bit 0 by masking out all other bits.
    //  while(!(...)) means "keep looping as long as it's NOT ready."
    //  The moment the FIFO has space, the loop exits.
    //
    //  x = don't care / could be 0 or 1, we only care about bit 0
    //
    while(!(ITM_STIMULUS_PORT0 & 1));


    ///////////////////////////////////////////////////////////////////////////////////
    //  STEP 4: DELIVER THE LETTER — Write the character into the FIFO
    ///////////////////////////////////////////////////////////////////////////////////
    //
    //  This is the moment it happens. We WRITE the character to the same register
    //  we just READ from (remember, it does double duty).
    //
    //  Example: sending 'H' (ASCII value 72, which is 0x48)
    //
    //    Bit:  31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0
    //          [0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  1  0  0  0]
    //                                                                                        ^        ^
    //                                                                                        |        |
    //                                                                          These bits = 0x48 = 72 = ASCII 'H'
    //
    //  After this line, the character is in the FIFO and HARDWARE TAKES OVER:
    //
    //     FIFO --> ITM --> TPIU --> SWO wire --> ST-LINK --> USB --> your PC
    //
    //  Your code does NOT have to do any of that.
    //  It just drops the character in the mailbox and moves on to the next one.
    //
    ITM_STIMULUS_PORT0 = ch;
}


/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
  return 1;
}

int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}




///////////////////////////////////////////////////////////////////////////////////////////
//  _write() function — lives in syscalls.c
//
//  THE CALL CHAIN:
//
//    YOUR CODE:        printf("Hello")          <-- you wrote this in main.c
//                          |
//    LIBRARY CODE:     printf internals         <-- pre-compiled C standard library
//                          |                        (provided by the toolchain, you never see this)
//                          |                        printf formats your string, then calls _write()
//                          |
//    SYSCALLS.C:       _write()                 <-- THIS FUNCTION. Loops through each character.
//                          |
//    SYSCALLS.C:       ITM_SendChar('H')        <-- drops each character into ITM FIFO
//                      ITM_SendChar('e')             one at a time
//                      ITM_SendChar('l')
//                      ITM_SendChar('l')
//                      ITM_SendChar('o')
//
//  You only write printf("Hello"). Everything below triggers automatically.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//  WHY DOES THIS FILE EXIST?
//
//  On your PC, when printf calls _write(), the OPERATING SYSTEM provides _write().
//  The OS knows how to talk to your terminal, your screen, your filesystem.
//  You never see it. You never modify it. It's locked away inside the OS libraries.
//
//  On the F407, THERE IS NO OS. Nobody provides _write().
//  That's why syscalls.c exists — YOU provide the functions that an OS would
//  normally provide.
//
//  Because you own _write(), you can change WHERE printf output goes:
//    - ITM_SendChar()  --> sends to ITM FIFO --> SWO wire --> ST-LINK --> your PC
//    - UART_SendChar() --> sends to a serial port (you'll learn this later)
//    - LCD_SendChar()  --> sends to an LCD screen
//    - anything you want!
//
//  On your PC, you CAN'T do this because the OS owns _write(), not you.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//  __attribute__((weak)):
//    This means "use this version of the function UNLESS someone provides
//    another version." It's a safety net — if the standard library already
//    has a _write, this one can be overridden. For now, don't worry about it.
//
//  Parameters:
//    file  --> which output stream (stdout, stderr, etc). We ignore this.
//    *ptr  --> pointer to the string data ("Hello")
//    len   --> how many characters to send (5 for "Hello")
//
//  Returns:
//    len   --> tells the caller how many characters were successfully written
//
///////////////////////////////////////////////////////////////////////////////////////////

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
    (void)file;  // We don't use 'file'. This line silences a compiler warning.
    int DataIdx;

    // Loop through each character in the string, one at a time.
    // For "Hello", this loops 5 times: H, e, l, l, o
    for (DataIdx = 0; DataIdx < len; DataIdx++)
    {
        // OLD LINE (commented out):
        // __io_putchar(*ptr++);
        //
        // This was the SEMIHOSTING path — the SLOW way.
        // Semihosting halts the processor every time it sends a character.
        // The processor stops, hands the character to the debugger over SWD
        // (the "stop and ask" protocol), then resumes. Very slow.

        // NEW LINE:
        ITM_SendChar(*ptr++);
        //
        // This is the ITM/SWO path — the FAST way.
        // Drops each character into the ITM FIFO.
        // The processor keeps running at full speed. No stopping.
        //
        // *ptr   = "get the character the pointer is currently pointing at"
        // ptr++  = "then move the pointer forward to the next character"
        //
        // So: first call gets 'H', next gets 'e', then 'l', 'l', 'o'
        //
        // After each character enters the FIFO, hardware takes over:
        //   FIFO --> ITM --> TPIU --> SWO wire --> ST-LINK --> USB --> your PC
    }
    return len;
}




int _close(int file)
{
  (void)file;
  return -1;
}


int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _isatty(int file)
{
  (void)file;
  return 1;
}

int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

int _stat(char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
